routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

/** ADMIN ROUTES */
Route::group(['middleware' => ['auth',], 'prefix' => 'admin'], function () {
    Route::get('/', [App\Http\Controllers\LeadController::class, 'index'])->name('admin');
    Route::get('/logs', [\Rap2hpoutre\LaravelLogViewer\LogViewerController::class, 'index'])->name('admin');

    Route::get('products', [App\Http\Controllers\ProductController::class, 'index'])->name('products');
    Route::get('product', [App\Http\Controllers\ProductController::class, 'create'])->name('product.create');
    Route::get('product/{sku}', [App\Http\Controllers\ProductController::class, 'show'])->name('product.show');
    Route::get('product/delete/{id}', [App\Http\Controllers\ProductController::class, 'delete'])->name('product.delete');
    Route::post('product', [App\Http\Controllers\ProductController::class, 'store'])->name('product.store');
    Route::put('product/{id}', [App\Http\Controllers\ProductController::class, 'update'])->name('product.update');

    Route::get('leads', [App\Http\Controllers\LeadController::class, 'index'])->name('leads');
    Route::post('lead', [App\Http\Controllers\LeadController::class, 'store'])->name('lead.store');
    Route::get('lead/{id}', [App\Http\Controllers\LeadController::class, 'show'])->name('lead.show');
    Route::put('lead/{id}', [App\Http\Controllers\LeadController::class, 'update'])->name('lead.update');
    Route::get('lead/delete/{id}', [App\Http\Controllers\LeadController::class, 'delete'])->name('lead.delete');

    Route::get('orders', [App\Http\Controllers\OrderController::class, 'index'])->name('leads');
    Route::get('order', [App\Http\Controllers\OrderController::class, 'create'])->name('order.create');
    Route::post('order', [App\Http\Controllers\OrderController::class, 'store'])->name('order.store');
    Route::get('order/{id}', [App\Http\Controllers\OrderController::class, 'show'])->name('order.show');
    Route::put('order/{id}', [App\Http\Controllers\OrderController::class, 'update'])->name('order.update');
    Route::get('order/delete/{id}', [App\Http\Controllers\OrderController::class, 'delete'])->name('order.delete');

    Route::get('customers', [App\Http\Controllers\CustomerController::class, 'index'])->name('customers');
    Route::get('customer', [App\Http\Controllers\CustomerController::class, 'create'])->name('order.create');
    Route::post('customer', [App\Http\Controllers\CustomerController::class, 'store'])->name('customer.store');
    Route::get('customer/{id}', [App\Http\Controllers\CustomerController::class, 'show'])->name('customer.show');
    Route::put('customer/{id}', [App\Http\Controllers\CustomerController::class, 'update'])->name('customer.update');
    Route::get('customer/delete/{id}', [App\Http\Controllers\CustomerController::class, 'delete'])->name('customer.delete');

    Route::get('payments', [App\Http\Controllers\PaymentController::class, 'index'])->name('payments');
    Route::get('payment', [App\Http\Controllers\PaymentController::class, 'create'])->name('order.create');
    Route::post('payment', [App\Http\Controllers\PaymentController::class, 'store'])->name('payment.store');
    Route::get('payment/{id}', [App\Http\Controllers\PaymentController::class, 'show'])->name('payment.show');
    Route::put('payment/{id}', [App\Http\Controllers\PaymentController::class, 'update'])->name('payment.update');
    Route::get('payment/delete/{id}', [App\Http\Controllers\PaymentController::class, 'delete'])->name('payment.delete');

    Route::get('switch-lang', [App\Http\Controllers\LanguageController::class, 'switchLang'])->name('switchLang');

    Route::get('/notify-leads', [App\Http\Controllers\LeadController::class, 'notifyLeads'])->name('instagramPosts');

    Route::get('logs', [\Rap2hpoutre\LaravelLogViewer\LogViewerController::class, 'index']);
});

Route::get('/instagram-feed', [App\Http\Controllers\PostController::class, 'instagramFeed'])->name('instagramPosts');


Route::get('{key}', function () {
    return view('welcome');
})->where('key', '.*');

app/Models/Customer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;

class Customer extends Model
{
    use HasFactory, Notifiable;

    protected $fillable = ['name', 'legal_name','rif','email','phone','address','city','contact',];

    public function getRifFormatedAttribute()
    {
        $rif = '';
        $arrayRif = str_split($this->rif);

        foreach ($arrayRif as $key => $char) {
         if ($key == 1 || $key == 9) {
             $rif .= '-';
            }
            $rif .= $char;

        }

        return $rif;
    }


}

app/Models/Order.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    use HasFactory;

    protected $fillable = ['customer_id', 'status', 'delivery_number', 'shipping_address', 'city' ,'state' ,'postal_code' ,'country' , 'tracking', 'comments'];

    public function customer()
    {
        return $this->belongsTo(Customer::class);
    }

    public function payment()
    {
        return $this->hasMany(Payment::class);
    }

    public function orderDetail()
    {
        return $this->hasMany(OrderDetail::class);
    }

    public function fee()
    {
        return $this->hasOne(FeeOrder::class);
    }

    //ATTRIBUTES

    public function getTotalAttribute()
    {
        $total = 0;
        foreach ($this->orderDetail as $detail) {
            $total += $detail->quantity * $detail->price;
        }

        return $total;
    }

    public function getPayedAttribute()
    {
        return $this->payment->sum('amount');
    }

}

app/Models/Payment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;

class Payment extends Model
{
    use HasFactory;

    protected $fillable = ['transaction_id', 'amount', 'name', 'email', 'status', 'trace',];

    public function order()
    {
        return $this->belongsTo(Order::class);
    }

    public function getPayerAttribute()
    {
        return $this->name ? $this->name : $this->order->customer->name;
    }
}

app/Http/Controllers/PaymentController.php
<?php

namespace App\Http\Controllers;

use App\Models\Customer;
use App\Models\Order;
use App\Models\Payment;
use App\Notifications\OrderNotification;
use Illuminate\Http\Request;

class PaymentController extends Controller
{
    public function index()
    {
        $payments = Payment::simplePaginate();

        if(request()->ajax()) {
            return $payments;
        }

        return view('admin.payments.index', compact('payments'));
    }

    public function create()
    {
        $payment = null;
        $orders = Order::where('status', '<>', 'PAYED')->get();
        return view('admin.payments.create', compact('orders',));
    }

    public function store()
    {
        if(!request()->ajax()) {
            request()->validate([
                'order_id' => 'required',
                'amount' => 'required',
                'status' => 'required',
                'type' => 'required',
            ]);
        }

        \Log::debug(request()->trace);

        $payment = new Payment();
        $payment->order_id = request()->order_id ? request()->order_id : $this->createOrder()->id;
        $payment->transaction_id = request()->transaction_id;
        $payment->amount = request()->amount;
        $payment->name = request()->name;
        $payment->email = request()->email;
        $payment->status = request()->status;
        $payment->trace = json_encode(request()->trace);
        $payment->type = request()->type ? request()->type : 'paypal';
        $payment->save();

        $message = __('validation.payment_created', ['name' => $payment->id]);

        $order = $payment->order;

        if(request()->ajax()) {

            $order->customer->notify(new OrderNotification($payment));
            return ['message' => $message];
        }

        if ($order->payed >= $order->total) {
            $order->status = 'PAYED';
            $order->save();
        }


        return redirect('/admin/payments')->with('success', $message);
    }

    public function show($id)
    {
        $payment = Payment::find($id);

        return view('admin.payments.show', compact('payment'));
    }

    public function delete($id)
    {
        $payment = Payment::find($id);
        $name = $payment->id;
        $payment->destroy($id);

        return redirect('/admin/payments')->with('success', __('validation.deleted', ['name ' => $name]));
    }

    private function createOrder()
    {
        if(request()->ajax()) {
            $shippingAddress = request()->trace['purchase_units'][0]['shipping']['address'];
            $line2 = isset($shippingAddress['address_line_2']) ? ' ' . $shippingAddress['address_line_2'] : '';
            $address = $shippingAddress['address_line_1'] . $line2;
        } else {
            $address = request()->customer['address'];
        }

        $order = new Order();
        $order->customer_id = $this->createCustomer()->id;
        $order->shipping_address = $address;
        $order->city = $shippingAddress['admin_area_2'];
        $order->state = $shippingAddress['admin_area_1'];
        $order->postal_code = $shippingAddress['postal_code'];
        $order->country = $shippingAddress['country_code'];
        $order->status = 'PAYED';

        $order->save();

        foreach (request()->items as $item) {
            $order->orderDetail()->create([
                'product_id' => $item['id'],
                'price' => $item['retail'],
                'quantity' => $item['quantity'],
            ]);
        }

        updateStockByOrder($order);

        return $order;
    }

    private function createCustomer()
    {
        if(request()->ajax()) {
            $email = request()->trace['purchase_units'][0]['payee']['email_address'];

            $fullShipping = request()->trace['purchase_units'][0]['shipping'];
            $name = $fullShipping['name']['full_name'];
            $shippingAddress = $fullShipping['address'];

            $line2 = isset($shippingAddress['address_line_2']) ? ' ' . $shippingAddress['address_line_2'] : '';
            $address = $shippingAddress['address_line_1'] . $line2 . ' ' . $shippingAddress['admin_area_2'] . ' ' . $shippingAddress['admin_area_1'] . ' ' . $shippingAddress['country_code'];
            $city = $shippingAddress['admin_area_2'];
        } else {
            $name = request()->customer['name'];
            $email = request()->customer['email'];
            $address = request()->customer['address'];
            $city = '';
        }

        $customer = Customer::where('email', $email)->first();

        if (!$customer) {
            $customer = new Customer();
            $customer->name = $name;
            $customer->email = $email;
            $customer->phone = request()->customer['phone'];
            $customer->address = $address;
            $customer->city = $city;

            $customer->save();
        }

        return $customer;
    }
}

resources/views/admin/payments/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif
            <div class="card">
                <div class="card-header"><h2>{{ __('validation.new_payment') }}</h2></div>
                @if (\Session::has('success'))
                <div class="alert alert-success">
                    {!! \Session::get('success') !!}
                </div>
                @endif

                <div class="card-body">
                    <form action="/admin/payment" method="POST">
                        @csrf
                        <div class="form-group">
                            <label for="order_id">{{ __('validation.order') }}</label>
                            <select class="form-control"  name="order_id" id="order_id">
                                <option value="">{{__('validation.select_order')}}</option>
                                @foreach ($orders as $order)
                                    @if (old('order_id') == $order->id)
                                        <option value="{{ $order->id }}" selected>{{ $order->customer->name }} {{ __('validation.order') }}: {{ $order->id }}</option>
                                    @else
                                        <option value="{{ $order->id }}">#{{ $order->id }} {{ $order->customer->name }} ${{ number_format($order->total - $order->payed,2,",",".")}}</option>
                                    @endif
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group">
                            <label for="amount">{{__('validation.attributes.amount')}}</label>
                            <input type="text" class="form-control" name="amount" id="amount" value="{{ old('amount') }}">
                        </div>

                        <div class="form-group">
                            <label for="status">{{ __('validation.attributes.status') }}</label>
                            <select class="form-control"  name="status" id="status">
                                <option value="">{{__('validation.select_status')}}</option>
                                <option value="completed" @if (old('status') == 'completed') selected @endif>{{ __('validation.completed') }}</option>
                                <option value="partial" @if (old('status') == 'partial') selected @endif>{{ __('validation.partial') }}</option>
                                <option value="in_process" @if (old('status') == 'in_process') selected @endif>{{ __('validation.in_process') }}</option>
                            </select>
                        </div>

                        <div class="form-group">
                            <label for="type">{{ __('validation.attributes.type') }}</label>
                            <select class="form-control"  name="type" id="type">
                                <option value="">{{__('validation.select_type')}}</option>
                                <option value="paypal" @if (old('type') == 'paypal') selected @endif>Paypal</option>
                                <option value="zelle" @if (old('type') == 'zelle') selected @endif>Zelle</option>
                                <option value="credit_card" @if (old('type') == 'credit_card') selected @endif>{{ __('validation.credit_card') }}</option>
                                <option value="cash" @if (old('type') == 'cash') selected @endif>{{ __('validation.cash') }}</option>
                                <option value="transfer" @if (old('type') == 'transfer') selected @endif>{{ __('validation.transfer') }}</option>
                            </select>
                        </div>

                        <div class="form-group">
                            <label for="trace">{{ __('validation.attributes.notes') }}</label>
                            <textarea class="form-control" id="trace" name="trace" rows="3">{{ old('trace') }}</textarea>
                        </div>

                        <button type="submit" class="btn btn-primary">{{ __('validation.submit') }}</button>
                      </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('styles')
    <style>
        label {
            text-transform: capitalize;
        }
    </style>
@endpush

resources/views/admin/payments/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <h2>
                        {{ __('menu.payments') }}
                        <a title="{{ __('validations.new_payment') }}" href="/admin/payment" class="float-right"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M13 2v9h9v2h-9v9h-2v-9h-9v-2h9v-9h2zm2-2h-6v9h-9v6h9v9h6v-9h9v-6h-9v-9z"/></svg></a>
                    </h2>


                </div>

                @if (\Session::has('success'))
                <div class="alert alert-success">
                    {!! \Session::get('success') !!}
                </div>
                @endif

                @if (\Session::has('error'))
                <div class="alert alert-danger">
                    {!! \Session::get('error') !!}
                </div>
                @endif

                @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
                @endif

                <div class="card-body">
                    <ul class="list-group">
                        @foreach ($payments as $payment)
                            <li class="list-group-item">
                                <b class="name">{{ $payment->id }}- </b>
                                <a href="/admin/payment/{{$payment->id}}" target="_blank">{{$payment->payer}} <b>{{ $payment->amount }}</b></a>
                                <a title="delete" href="#" data-name="{{ $payment->id }}" data-url="/admin/payment/delete/{{$payment->id}}" class="float-right delete-row">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M3 6v18h18v-18h-18zm5 14c0 .552-.448 1-1 1s-1-.448-1-1v-10c0-.552.448-1 1-1s1 .448 1 1v10zm5 0c0 .552-.448 1-1 1s-1-.448-1-1v-10c0-.552.448-1 1-1s1 .448 1 1v10zm5 0c0 .552-.448 1-1 1s-1-.448-1-1v-10c0-.552.448-1 1-1s1 .448 1 1v10zm4-18v2h-20v-2h5.711c.9 0 1.631-1.099 1.631-2h5.315c0 .901.73 2 1.631 2h5.712z"/></svg>
                                </a>
                            </li>
                        @endforeach
                      </ul>
                      <br>
                      <div class="mx-auto">
                          {{ $payments->links() }}
                      </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/payments/show.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ __('validation.payment_receipt') }} #{{ $payment->id }} </title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
</head>
<style>
    * {
        margin: 0;
        padding: 0;
        margin-block-start: 0;
        margin-block-end: 0;
        margin-inline-start: 0;
        margin-inline-end: 0;
    }

    .container {
        max-width: 750px;
        margin: 0 auto;
        font-family: Roboto, arial;
    }

    .wrapper {
        padding: 0 60px;
    }

    .logo {
        width: 27%;
        margin: 0 26% 0 0;
    }

    .logo img {
        margin: 0 auto;
        width: 100%;
    }

    .enterprise {
        margin-top: 26px;
    }

    h2 {
        color: #528CC7;
        font-size: 14px;
        font-weight: 700;
        margin-bottom: 6px;
    }

    .middle {
        margin-top: 8px;
    }

    h3 {
        font-size: 13px;
        margin-bottom: 8px;
    }

    h4 {
        color: #a09b9b;
        font-size: 12px;
        margin-bottom: 8px;
    }

    h5 {
        color: #528CC7  ;
        font-size: 29px;
        font-weight: 700;
    }

    h6 {
        font-size: 20px
    }

    p {
        color: #444242;
        font-size: 11px;
        line-height: 1.3;
        margin-bottom: 6px;
    }

    b {
        font-weight: 700;
        font-size: 12px
    }

    .pink {
        font-weight: 700;
        color: #DE106E;
    }

    .top {
        bpayment-top: 8px solid #528CC7;
    }

    .info {
        margin-top: 28px;
    }

    .col {
        width: 45%;
    }

    .paddingLeft {
        padding-left: 10%;
    }

    .top, .info {
        display: flex;
        -ms-justify-content: flex-start;
        justify-content: flex-start;
        -ms-align-items: flex-start;
        align-items: flex-start;
        -ms-align-content: flex-start;
        align-content: flex-start;
        flex-wrap: wrap;
        flex-direction: row;
    }

    table {
        width: 100%;
    }

    tr:nth-child(even) {
        padding: 10px;
        background-color: #F3F3F3;
        -webkit-print-color-adjust: exact;
    }

    th {
        text-align: left;
        color: #528CC7;
        font-weight: 700;
        text-transform: capitalize;
        font-size: 14px
    }

    td {
        font-size: 11px;
    }

    td, th {
        padding: 10px 10px 10px 0;
    }

    .center {
        text-align: center;
    }

    .right {
        text-align: right;
    }

</style>
<body>
    <div class="container">
        <div class="wrapper">
            <div class="top">
                <h1 class="logo"><img src="{{ asset('img/color-logo.png')}}" alt="Logo"></h1>
                <div class="enterprise">
                    <h2>ADEMIA ADMINISTRACION & IT , C.A</h2>
                    <p>RIF: J-41131208-8</p>
                    <p>AV URDANETA EDIFICIO FONDO COMÚN OFC 16-B</p>
                    <p>CARACAS</p>
                    <p>(0212) 5736017</p>
                    <p>(0414) 9900552</p>
                </div>
            </div>
            <div class="middle">
                <h5>{{__('validation.payment_receipt')}}</h5>
                <p class="pink">{{ __('validation.payment_date')}}: {{ $payment->created_at->format('d-m-Y') }}</p>
            </div>

            <div class="info">
                <div class="col">
                    <h3>{{__('validation.customer')}}</h3>
                    <h4>{{ $payment->payer }}</h4>
                    <p class="address">{{ $payment->order->shipping_address ? $payment->order->shipping_address : $payment->order->customer->address }}</p>
                </div>
                <div class="col paddingLeft">
                @if ($payment->order->customer->rif)
                    <p><b>RIF</b></p>
                    <p>{{ $payment->order->customer->rif_formated }}</p>
                @endif
                @if ($payment->order->customer->contact)
                    <p><b>{{__('validation.lead_contact')}}</b></p>
                    <p><p>{{ $payment->order->customer->contact }}</p></p>
                @endif
                </div>
            </div>
            <div class="detail">
                <table>
                    <tr>
                        <th>{{ __('validation.attributes.description') }}</th>
                        <th>{{ __('validation.payment_type') }}</th>
                        <th class="right">Total</th>
                    </tr>
                    <tr>
                        <td>{{ __('validation.payment_description', ['name' => $payment->payer]) }} #{{ $payment->order->delivery_number ? $payment->order->delivery_number :$payment->order->id}}</td>
                        <td>{{ __('validation.' . $payment->type) }}</td>
                        <td class="right">{{ number_format($payment->amount,2,",",".") }}</td>
                    </tr>

                    <tr>
                        <td></td>
                        <th class="right">{{ __('validation.subtotal') }}</th>
                        <th class="right">{{ number_format($payment->amount,2,",",".") }}</th>
                    </tr>
                </table>
                <h6 class="pink right">{{ number_format($payment->amount,2,",",".") }}</h6>
            </div>
            <div class="bottom">
            @if ($payment->trace)
                <p>{{ __('validation.notes') }}</p>
                <p>{{ $payment->trace }}</p>
            @endif
            </div>
        </div>
    </div>
</body>
</html>